'use client'

import { useEffect, useRef, useState } from 'react'
import { Send, X } from 'lucide-react'

type Mood = 'idle' | 'writing' | 'thinking' | 'celebrating' | 'alert'
type Prefs = { name: string; appearance: 'male' | 'female'; enabled: boolean; reducedMotion: boolean; size: 'small' | 'normal' | 'large'; position?: { x: number; y: number } }
type Signal = { mood?: Mood; message?: string }
const KEY = 'lc_author_companion_v1'
const defaults: Prefs = { name: 'Scholar', appearance: 'male', enabled: true, reducedMotion: false, size: 'normal' }
export function dispatchCompanionSignal(signal: Signal) { if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent<Signal>('lc-companion-signal', { detail: signal })) }

export function LCAuthorCompanion({ projectName, isProjectWorkspace, onOpenChat }: { projectName?: string | null; isProjectWorkspace: boolean; onOpenChat: () => void; onOpenProjects: () => void }) {
  const [ready, setReady] = useState(false); const [prefs, setPrefs] = useState<Prefs>(defaults); const [mood, setMood] = useState<Mood>('idle'); const [chatOpen, setChatOpen] = useState(false); const [settingsOpen, setSettingsOpen] = useState(false); const [prompt, setPrompt] = useState(''); const [bubble, setBubble] = useState(''); const [face, setFace] = useState({ x: 0, y: 0 }); const drag = useRef<{ x: number; y: number } | null>(null); const mascot = useRef<HTMLDivElement>(null); const lastDragUpdate = useRef(0)
  useEffect(() => { try { const v = localStorage.getItem(KEY); if (v) setPrefs({ ...defaults, ...JSON.parse(v) }) } catch {} setReady(true) }, [])
  useEffect(() => { if (!ready) return; const timer = window.setTimeout(() => { try { localStorage.setItem(KEY, JSON.stringify(prefs)) } catch {} }, 250); return () => window.clearTimeout(timer) }, [prefs, ready])
  useEffect(() => { const fn = (e: Event) => { const s = (e as CustomEvent<Signal>).detail; if (s?.mood) setMood(s.mood); if (s?.message) { setBubble(s.message); setTimeout(() => setBubble(''), 3500) } }; window.addEventListener('lc-companion-signal', fn); return () => window.removeEventListener('lc-companion-signal', fn) }, [])
  useEffect(() => { const move = (e: PointerEvent) => { if (!drag.current) { const r = mascot.current?.getBoundingClientRect(); if (!r) return; setFace({ x: Math.max(-4, Math.min(4, (e.clientX-(r.left+r.width/2))/80)), y: Math.max(-3, Math.min(3, (e.clientY-(r.top+r.height/2))/80)) }); return } const now = performance.now(); if (now - lastDragUpdate.current < 16) return; lastDragUpdate.current = now; const w = mascot.current?.offsetWidth || 250; setPrefs(p => ({ ...p, position: { x: Math.max(12, Math.min(window.innerWidth-w-12, e.clientX-drag.current!.x)), y: Math.max(12, Math.min(window.innerHeight-120, e.clientY-drag.current!.y)) } })) }; const up = () => { drag.current = null }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); window.addEventListener('pointercancel', up); return () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); window.removeEventListener('pointercancel', up) } }, [])
  if (!ready) return null
  const scale = prefs.size === 'small' ? .78 : prefs.size === 'large' ? 1.22 : 1
  function save(next: Partial<Prefs>) { setPrefs(p => ({ ...p, ...next })) }
  function send() { const text = prompt.trim(); if (!text) return; if (isProjectWorkspace) { window.dispatchEvent(new CustomEvent('lc-companion-prompt', { detail: { prompt: text } })); setBubble('Prompt placed in your project co-pilot.'); setMood('thinking') } else { onOpenChat(); setBubble('Chat opened.'); } setPrompt('') }
  if (!prefs.enabled) return <button onClick={() => save({ enabled: true })} className="fixed bottom-5 right-5 z-[10020] rounded-full bg-blue-600 px-3 py-2 text-xs text-white shadow-xl">Restore companion</button>
  return <aside ref={mascot} style={{ left: prefs.position?.x, top: prefs.position?.y, transform: `scale(${scale})`, transformOrigin: 'top left' }} className={`fixed ${prefs.position ? '' : 'bottom-8 right-8'} z-[10020] flex w-80 flex-col items-center select-none`} aria-label="Writing companion">
    {bubble && <div className="absolute -top-10 z-30 rounded-full border border-zinc-800 bg-zinc-950 px-3 py-1.5 text-xs text-zinc-100 shadow-2xl">{bubble}</div>}
    <div onPointerDown={e => { if (e.button !== 0 || (e.target instanceof Element && e.target.closest('button,input'))) return; const node = mascot.current; if (!node) return; e.preventDefault(); e.currentTarget.setPointerCapture?.(e.pointerId); const r = node.getBoundingClientRect(); drag.current = { x: e.clientX-r.left, y: e.clientY-r.top }; setBubble('Wheee! Moving around!') }} className={`relative h-56 w-56 cursor-grab touch-none ${prefs.reducedMotion ? '' : 'lc-ref-bob'}`}>
      {[['left-[22%] top-[12%] bg-cyan-400'],['right-[26%] top-[8%] bg-blue-400'],['left-[15%] top-[34%] bg-purple-400'],['right-[14%] top-[28%] bg-indigo-400']].map(([classes], i) => <button key={i} onPointerDown={e=>e.stopPropagation()} onClick={()=>setSettingsOpen(true)} className={`lc-ref-dot absolute ${classes} z-20 h-3.5 w-3.5 rounded-full border-2 border-black`} aria-label="Open companion settings" />)}
      <Mascot appearance={prefs.appearance} mood={mood} face={face} onPhone={() => setChatOpen(v => !v)} />
    </div>
    {chatOpen && <div onPointerDown={e=>e.stopPropagation()} className="mt-2 flex w-80 flex-col gap-2 rounded-2xl border border-zinc-800 bg-zinc-950/95 p-3 shadow-2xl backdrop-blur-md">
      <div className="flex items-center justify-between border-b border-zinc-900 pb-2 text-[11px] font-mono text-zinc-400"><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-emerald-400" />{prefs.name} Phone Active</span><button onClick={()=>setChatOpen(false)} aria-label="Close companion chat" className="p-1 text-zinc-400 hover:text-white"><X className="h-3.5 w-3.5" /></button></div>
      <div className="rounded-lg border border-zinc-800 bg-zinc-900/80 p-2 text-[11px] text-zinc-400">💬 <b className="text-sky-400">{prefs.name}:</b> Type a prompt for your co-pilot.</div>
      <div className="flex items-center rounded-xl border border-zinc-800 bg-zinc-900 px-2.5 py-1.5 focus-within:border-sky-500"><input value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Type a message or prompt..." className="min-w-0 flex-1 bg-transparent text-xs text-white outline-none"/><button onClick={send} className="rounded-lg bg-blue-600 p-1.5 text-white"><Send className="h-3.5 w-3.5" /></button></div>
    </div>}
    {settingsOpen && <Settings prefs={prefs} save={save} mood={mood} setMood={setMood} close={()=>setSettingsOpen(false)} />}
  </aside>
}

function Settings({ prefs, save, mood, setMood, close }: { prefs: Prefs; save:(v:Partial<Prefs>)=>void; mood:Mood; setMood:(v:Mood)=>void; close:()=>void }) { return <div onPointerDown={e=>e.stopPropagation()} className="absolute left-1/2 top-1/2 z-50 w-[min(22rem,92vw)] -translate-x-1/2 rounded-2xl border border-zinc-800 bg-zinc-950 p-4 shadow-2xl"><div className="mb-3 flex justify-between"><b className="text-sm">Mascot settings</b><button onClick={close}><X className="h-4 w-4" /></button></div><label className="block text-xs text-zinc-400">Name<input value={prefs.name} onChange={e=>save({name:e.target.value})} className="mt-1 w-full rounded bg-zinc-900 p-2 text-white" /></label><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>save({appearance:'male'})} className={prefs.appearance==='male'?'rounded bg-blue-600 p-2 text-xs':'rounded bg-zinc-900 p-2 text-xs'}>Male</button><button onClick={()=>save({appearance:'female'})} className={prefs.appearance==='female'?'rounded bg-blue-600 p-2 text-xs':'rounded bg-zinc-900 p-2 text-xs'}>Female</button></div><div className="mt-3 flex justify-between text-xs"><label>Reduced motion <input type="checkbox" checked={prefs.reducedMotion} onChange={e=>save({reducedMotion:e.target.checked})}/></label><label>Turn off <input type="checkbox" checked={!prefs.enabled} onChange={e=>save({enabled:!e.target.checked})}/></label></div><div className="mt-3 grid grid-cols-3 gap-1">{(['small','normal','large'] as const).map(s=><button key={s} onClick={()=>save({size:s})} className={prefs.size===s?'rounded bg-blue-600 p-2 text-xs':'rounded bg-zinc-900 p-2 text-xs'}>{s}</button>)}</div><div className="mt-3 grid grid-cols-4 gap-1">{(['idle','writing','thinking','celebrating'] as Mood[]).map(s=><button key={s} onClick={()=>setMood(s)} className={mood===s?'rounded bg-blue-600 p-2 text-[10px]':'rounded bg-zinc-900 p-2 text-[10px]'}>{s}</button>)}</div></div> }

function Mascot({ appearance, mood, face, onPhone }: { appearance: 'male'|'female'; mood:Mood; face:{x:number;y:number}; onPhone:()=>void }) { const text=mood==='thinking'?'? !':mood==='writing'?'✎ …':mood==='celebrating'?'^ ^':'> _'; const color=appearance==='female'?'#c084fc':'#3b82f6'; return <svg viewBox="0 0 120 120" className="h-full w-full drop-shadow-2xl"><ellipse cx="60" cy="112" rx="30" ry="5" fill="#000" opacity=".6"/><path d="M44 100c0 8 8 8 8 0m16 0c0 8 8 8 8 0" fill={color} stroke="#111827" strokeWidth="2.5"/><path d="M38 82c-10 2-10 13-2 12m46-12c11-2 13 9 5 12" fill="none" stroke={color} strokeWidth="9" strokeLinecap="round"/><rect x="42" y="76" width="36" height="26" rx="10" fill={color} stroke="#111827" strokeWidth="2.5"/><path d="M32 68C20 68 16 52 28 42 20 30 36 16 50 24c8-10 26-10 32 0 16-6 24 8 16 22 10 10 2 25-10 22Z" fill={color} stroke="#111827" strokeWidth="3"/><rect x="36" y="36" width="48" height="32" rx="10" fill="#0b1220" stroke="#111827" strokeWidth="2.5"/><g transform={`translate(${face.x} ${face.y})`}><text x="60" y="56" textAnchor="middle" fontFamily="monospace" fontSize="16" fontWeight="bold" fill="#38bdf8">{text}</text></g>{appearance==='female'&&<path d="M78 22c-8-6-9 6 0 4 9 2 8-10 0-4Z" fill="#ec4899" stroke="#111827"/>}{mood==='writing'&&<path d="m84 75 8 18" stroke="#fbbf24" strokeWidth="4"/>}<g onClick={e=>{e.stopPropagation();onPhone()}} className="cursor-pointer"><rect x="86" y="78" width="12" height="20" rx="3" fill="#090d16" stroke="#38bdf8" strokeWidth="1.4"/><rect x="88" y="81" width="8" height="12" rx="1" fill="#0284c7"/></g></svg> }
